### ISSUE TITLE
[ICON]: Terraform files

### ISSUE THREAD

**Issue by jcanabarro** [392781/vscode-runescape-icon-theme#2]
### File Type

*.tf, .terraform.lock.hcl

### (Optional) Propose an Icon

Thoughts on something like:
1. https://oldschool.runescape.wiki/w/Plank_Make
2. https://oldschool.runescape.wiki/w/Kharyrll_Teleport

Mostly because is an infrastructure construction or the teleport animations that create blocks.

**Comment by 392781** [comment]
Since its infrastructure as code software, another option would be the Construction icon or Farming icon.

That said to fit in the theme of "terraforming" another option would be the [Geomancy spell](https://oldschool.runescape.wiki/w/Geomancy) (looks pretty neat too).

**Comment by jcanabarro** [comment]
Yes, Geomancy seem a pretty good icon for it.

**Comment by 392781** [comment]
Completed with commit 9a2566f
