### ISSUE TITLE
[ICON]: Svelte Files

### ISSUE THREAD

**Issue by jaroldo3** [392781/vscode-runescape-icon-theme#6]
### File Type

.svelte

### (Optional) Propose an Icon

https://oldschool.runescape.wiki/w/Zenyte

**Comment by 392781** [comment]
Thanks for the suggestion! My only reservation with this is that zenyte looks rather similar to ruby which is used for .rb files.  That said, I personally don't have any good ideas for icons for svelte file types... 

I'll think about this once my school quarter ends but until then, I'm open to more suggestions :^)

**Comment by jaroldo3** [comment]
Makes sense. We went with Zenyte because Svelte is an orange icon so we tried to keep with that direction. I know there are things like Zenyte bracelet, ring, necklace if any of those work. We were also going down the path of other orange items like anti-dragon shield

**Comment by 392781** [comment]
I decided to go with uncut Zenyte.  It seems like a nice icon for `.svelt` files afterall. It'll be added in the next release coming this week :^)

(Sorry for the delay... life's been busy)

**Comment by 392781** [comment]
Completed with [c5406a8](https://github.com/392781/vscode-runescape-icon-theme/commit/c5406a87eb589ee841a2be9ecc31a5c3bd47ae29)
