### ISSUE TITLE
[ICON]: OpenGL shader files

### ISSUE THREAD

**Issue by kekobleibtkeko** [392781/vscode-runescape-icon-theme#8]
### File Type

.vs, .fs, .comp

### (Optional) Propose an Icon

My idea would be the use of fish for the icons, here's why:
- vertex shaders are (in a way) just "uncooked" shaders, while fragment shaders are more "cooked", further along in the graphics pipeline
- `.fs` is very close to `fish`
- for compute (`.comp`) shaders, a lot of computation can be done, so something like an octopus could be fitting. Much computation; smart fish, many arms
- A somewhat common application for shaders are boids, which typically feature fish swimming

vertex shader suggestion -https://oldschool.runescape.wiki/w/Raw_cod
fragment shader suggestion -https://oldschool.runescape.wiki/w/Salmon
compute shader suggestion -https://oldschool.runescape.wiki/w/Raw_karambwan

Yes, the fragment and vertex shaders are different fish, but I'd argue that having the two of them be distinct colors is important.
Thanks for the neat icon set so far!

**Comment by 392781** [comment]
I like this idea. To be honest, the icons don't need to be entirely consistent (same type of fish, same type of genre, etc.).

Personally, I think we can choose a cooler fish than cod for `.vs`... Bass maybe? On the same note, I'm not sure about `.fs` being the same shape fish as vertex shaders... Again, for the cool factor, let's consider other fish types. I'm open to recommendations!

I do like the idea of using the karambwan for compute shaders, it's a cool icon and I like the context you gave for it haha

**Comment by kekobleibtkeko** [comment]
True, a bass would be a lot more interesting, and at that note looking over the list of fish again for `.fs`, the cooked Rainbow fish stands out nicely with it's vibrant colors which would fit thematically with how fragment shaders are responsible for actually getting color onto the screen. Cut Sacred eel and prepared Tetra would be other alternatives I'd find fitting too.

**Comment by 392781** [comment]
Let's do

* bass -> .vs
* rainbow fish -> .fs
* karambwan -> .comp

I'm gonna make the changes sometime this week. 

Thanks for your suggestions!

**Comment by kekobleibtkeko** [comment]
Nice, sounds good!
Cheers :)

**Comment by 392781** [comment]
DONE 1b323e1b839bb4a1cba226980ad051c72adafebf! Icons updated to v1.2.0!

**Comment by 392781** [comment]
Gonna add a dark mode option for `.comp` since raw karambwan is a little to dark to see.
